version: "3"

services:

  ui:
    image: jcpaiva/tradenetworks-ui
    container_name: tradenetworks-ui
    restart: unless-stopped
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    ports:
      - "8081:8080"
    networks:
      - tradenetworks-network

  db:
    image: jcpaiva/tradenetworks-db
    container_name: tradenetworks-db
    restart: unless-stopped
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SA_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./volumes/database/data:/var/opt/mssql
      - ./volumes/database/backups:/backups
    networks:
      - tradenetworks-network

volumes:
  tradenetworks-data:

networks:
  tradenetworks-network:
    driver: bridge
