version: "3"

services:

  proxy:
    image: nginx:alpine
    container_name: tradenetworks-proxy
    restart: unless-stopped
    volumes:
      - ./volumes/proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ui
    links:
      - ui
    ports:
      - "80:80"
      - "443:443"
    networks:
      - tradenetworks-network

  ui:
    image: jcpaiva/tradenetworks-ui
    container_name: tradenetworks-ui
    restart: unless-stopped
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - tradenetworks-network

  db:
    image: jcpaiva/tradenetworks-db
    container_name: tradenetworks-db
    restart: unless-stopped
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SA_PASSWORD=${DB_PASSWORD}
    volumes:
      - tradenetworks-data:/var/opt/mssql
      - ./volumes/database/backups:/backups
    ports:
      - "1433:1433"
    networks:
      - tradenetworks-network

volumes:
  tradenetworks-data:

networks:
  tradenetworks-network:
    driver: bridge
